[tool.poetry]
name = "mbdata"
version = "26.0.0"
description = ""
authors = ["Lukáš Lalinský <lalinsky@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
SQLAlchemy = "^1.4.29"
Flask = "^2.0.2"
lxml = "^4.7.1"
psycopg2 = "^2.9.2"
sqlparse = "^0.4.2"
six = "^1.16.0"
pysolr = "^3.9.0"

[tool.poetry.dev-dependencies]
nose = "^1.3.7"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
